version: '3.9'

volumes:
  jenkins-docker-certs:
  jenkins-data:


networks:
  jenkins_network:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    mem_limit: 4g
